version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: medicar_backend/
    command: bash -c "python3 medicar_backend/manage.py makemigrations && python3 medicar_backend/manage.py migrate && python3 medicar_backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  # angular:
  #   build: MedicarFrontend/
  #   command: bash -c "npm start"
  #     - .:front
  #   ports:
  #     - "8010:80"
